# Generated by Django 4.2 on 2023-04-14 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Product Title",
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Product Slug",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Product Description",
                        max_length=1000,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(1000)],
                        verbose_name="Description",
                    ),
                ),
                (
                    "qty",
                    models.IntegerField(
                        default=1, help_text="Product Quantity", verbose_name="Quantity"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Product Price",
                        max_digits=6,
                        verbose_name="Price",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is Product Active", verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created at", verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Updated Time", verbose_name="Updated Time"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
