# Generated by Django 4.2 on 2023-04-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="original_price",
        ),
        migrations.AddField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(
                decimal_places=2,
                default=1000,
                help_text="Sale Price",
                max_digits=6,
                verbose_name="Sale Price",
            ),
            preserve_default=False,
        ),
    ]
