# Generated by Django 4.2 on 2023-04-15 23:09

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_product_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="categories",
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=mptt.fields.TreeManyToManyField(
                help_text="Product Categories", related_name="products", to="product.category"
            ),
        ),
    ]
