# Generated by Django 4.2 on 2023-04-17 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_remove_product_categories_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Brand Name", max_length=50, verbose_name="Name"
                    ),
                ),
                ("slug", models.SlugField(help_text="Brand Slug", verbose_name="Slug")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                help_text="Product Brand",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brand",
                to="product.brand",
            ),
        ),
    ]
