# Generated by Django 4.2 on 2023-04-18 19:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_brand_product_brand"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Product SKU",
                        max_length=8,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(6)],
                        verbose_name="SKU",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("kg", "Kilogram"), ("number", "Number"), ("box", "Box")],
                        help_text="Unit",
                        max_length=20,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "amount",
                    models.SmallIntegerField(
                        default=1, help_text="Amount", verbose_name="Amount"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unit Price",
                        max_digits=5,
                        verbose_name="Unit Price",
                    ),
                ),
                (
                    "tax_rate",
                    models.FloatField(
                        choices=[(1, "%1"), (8, "%8"), (18, "%18")],
                        help_text="Tax Rate",
                        verbose_name="Tax Rate",
                    ),
                ),
                (
                    "profit_rate",
                    models.FloatField(
                        default=20, help_text="Profit Rate", verbose_name="Profit"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created At", verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        editable=False, help_text="Updated At", verbose_name="Updated At"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product",
                        to="product.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock List",
                "verbose_name_plural": "Stock List",
                "ordering": ["-created_at"],
            },
        ),
    ]
