# Generated by Django 4.2 on 2023-04-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Updated At", verbose_name="Updated At"
            ),
        ),
    ]
