# Generated by Django 4.2 on 2023-04-18 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_alter_stock_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="qty",
        ),
    ]
