# Generated by Django 4.2 on 2023-04-18 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_remove_product_qty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="product",
            field=models.OneToOneField(
                help_text="Product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="product.product",
                verbose_name="Product",
            ),
        ),
    ]
